#!/bin/bash
echo "SCRM数据导入任务归档快速访问"
echo "=============================="
echo ""
echo "归档位置: $(pwd)/SCRM数据导入任务_归档/"
echo ""
echo "快速访问命令:"
echo "1. 查看归档索引: cat SCRM数据导入任务_归档/归档索引.md"
echo "2. 查看数据文件: ls -la SCRM数据导入任务_归档/数据文件/"
echo "3. 查看邮件内容: cat SCRM数据导入任务_归档/邮件内容/SCRM数据导入邮件内容_*.txt"
echo "4. 查看任务总结: cat SCRM数据导入任务_归档/报告文档/SCRM数据导入任务_最终总结.md"
echo ""
echo "重要文件:"
echo "- 数据导入文件: SCRM数据导入任务_归档/数据文件/SCRM_*_数据_已处理_*.xlsx"
echo "- 邮件内容: SCRM数据导入任务_归档/邮件内容/SCRM数据导入邮件内容_*.txt"
echo "- 任务总结: SCRM数据导入任务_归档/报告文档/SCRM数据导入任务_最终总结.md"
